include_recipe '../cookbooks/homebrew/default'
include_recipe '../cookbooks/ssh/default'
include_recipe '../cookbooks/git/default'
include_recipe '../cookbooks/zsh/default'
include_recipe '../cookbooks/tmux/default'
include_recipe '../cookbooks/neovim/default'
include_recipe '../cookbooks/ruby/default'
